### ISSUE TITLE
not necessarily a "server"

### ISSUE THREAD

**Issue by tiagocpontesp** [kgram/webpack-node-dev#1]
:)

**Comment by kgram** [comment]
I'm not sure what you mean. I started out by writing "server process" everywhere in the readme, but I changed that to "node process" or just "process" as one of the first releases. Now there's only one reference to server in the readme, that `waitForOutput` is useful for servers. 

Did I miss a reference somewhere? Could you be a bit more specific?

**Comment by tiagocpontesp** [comment]
I just noticed that in the code it says server everywhere, e.g.: https://github.com/kgram/webpack-node-dev/blob/master/index.js#L126

**Comment by kgram** [comment]
Huh, could have sworn I'd taken care of that. Should be fixed now. Thanks for the heads up :)

Since you're my first ticket and thus my first possibility for asking: can I ask what you're using the package for and how you like it? Does everything make sense?

**Comment by tiagocpontesp** [comment]
Sorry was away from github until now. 
I'll let you know if it's all working when I integrate it :)

I have a dev script relying on a few processes running [concurrently](https://github.com/kimmobrunfeldt/concurrently).
Apart from a `webpack-dev-server` app, I want two node processes running on `buildEnd`: 
- The db bootstrapping program, which exits by itself. 
- The web server program, which needs restarting.

I've been doing just this with [WebpackShellPlugin](https://github.com/1337programming/webpack-shell-plugin), manually taking care of `pid`s and `kill`s -- but your module should allow for simpler code. 

:) thank you!
